# Generated by Django 4.2.2 on 2023-08-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vending", "0002_vendingmachineslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
