# Generated by Django 4.2.2 on 2023-08-07 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vending", "0005_buyer_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="email",
        ),
    ]
